# Generated by Django 5.2.8 on 2025-12-02 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(help_text='The uploaded document file', upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original filename of the uploaded document', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_format', models.CharField(help_text='File format/extension (e.g., pdf, jpg, png)', max_length=10)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('id_document', 'ID Document'), ('bank_statement', 'Bank Statement'), ('hr_form', 'HR Form'), ('other', 'Other')], default='other', help_text='Type of document', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Time taken to process in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Document being processed', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='documents.document')),
            ],
            options={
                'verbose_name': 'Extraction Job',
                'verbose_name_plural': 'Extraction Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(help_text='Structured extracted data as JSON')),
                ('overall_confidence', models.FloatField(default=0.0, help_text='Overall confidence score (0-1)')),
                ('field_confidence', models.JSONField(blank=True, default=dict, help_text='Confidence scores for individual fields')),
                ('extraction_method', models.CharField(default='manual', help_text='Method used for extraction (e.g., ocr, ai, manual)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extraction_job', models.OneToOneField(help_text='The extraction job that produced this data', on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='documents.extractionjob')),
            ],
            options={
                'verbose_name': 'Extracted Data',
                'verbose_name_plural': 'Extracted Data',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-uploaded_at'], name='documents_d_uploade_78ffff_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-uploaded_at'], name='documents_d_user_id_2d1909_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['-created_at'], name='documents_e_created_1f5c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['document', '-created_at'], name='documents_e_documen_aadf3e_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['status'], name='documents_e_status_5337af_idx'),
        ),
    ]
