# Generated by Django 5.2.8 on 2025-12-03 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='doc_uploaded_idx',
            old_name='documents_d_uploade_78ffff_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='doc_user_uploaded_idx',
            old_name='documents_d_user_id_2d1909_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='doc_type_idx',
            old_name='documents_d_documen_40c475_idx',
        ),
        migrations.RenameIndex(
            model_name='extractionjob',
            new_name='job_created_idx',
            old_name='documents_e_created_1f5c8b_idx',
        ),
        migrations.RenameIndex(
            model_name='extractionjob',
            new_name='job_doc_created_idx',
            old_name='documents_e_documen_aadf3e_idx',
        ),
        migrations.RenameIndex(
            model_name='extractionjob',
            new_name='job_status_idx',
            old_name='documents_e_status_5337af_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('id_document', 'ID Document'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('bank_statement', 'Bank Statement'), ('hr_form', 'HR Form'), ('medical_record', 'Medical Record'), ('tax_form', 'Tax Form'), ('legal_document', 'Legal Document'), ('certificate', 'Certificate'), ('letter', 'Letter'), ('report', 'Report'), ('form', 'Form'), ('other', 'Other')], default='other', help_text='Type of document', max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'document_type'], name='doc_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_format'], name='doc_format_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'file_format'], name='doc_user_format_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['status', '-created_at'], name='job_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['document', 'status'], name='job_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['completed_at'], name='job_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['processing_time_seconds'], name='job_proc_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gt', 0)), name='doc_positive_file_size'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_format__in', ['pdf', 'jpg', 'jpeg', 'png', 'tiff', 'bmp', 'webp'])), name='doc_valid_file_format'),
        ),
        migrations.AddConstraint(
            model_name='extractionjob',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__gte', 0)), name='job_non_negative_retry'),
        ),
        migrations.AddConstraint(
            model_name='extractionjob',
            constraint=models.CheckConstraint(condition=models.Q(('processing_time_seconds__isnull', True), ('processing_time_seconds__gt', 0), _connector='OR'), name='job_positive_proc_time'),
        ),
        migrations.AddConstraint(
            model_name='extractionjob',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='job_valid_timestamps'),
        ),
    ]
